title: Fresh Brew Coffee Co! # your name (or website title) here
logo: "/images/mug.PNG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 This is Fresh Brew Coffee Co. serving the best beans 

  <br><br>
  <a href="https://njit-wis.github.io/coffee_site/about">About Fresh Brew Coffee Co.</a>
  <br><br> 
  <a href="https://njit-wis.github.io/coffee_site/blog">Blog</a>
  <br><br>
  <a href="https://njit-wis.github.io/coffee_site/brand_journey">Brand Journey</a>
  <br><br>
  <a href="https://njit-wis.github.io/coffee_site/subscribe">Subscribe</a>
  <br><br>
  <a href="https://njit-wis.github.io/coffee_site/privacy_policy">Privacy Policy</a>
  
theme: jekyll-theme-minimal
google_analytics: G-LG6PBB02Q5 # your Google Analytics tracking ID here
